import React from "react";
import type { PostMortemReport } from "../../api/types";
import { FileText, Calendar, CheckSquare, Shield, Download } from "lucide-react";

interface PostMortemViewerProps {
  report: PostMortemReport;
}

export const PostMortemViewer: React.FC<PostMortemViewerProps> = ({ report }) => {
  const handleDownload = () => {
    if (!report) return;
    const content = `
INCIDENT POST-MORTEM REPORT
===========================

EXECUTIVE SUMMARY
${report.executiveSummary}

IMPACT ASSESSMENT
${report.impactAssessment}

ROOT CAUSE
${report.rootCauseSummary}

REMEDIATION
${report.remediationSummary}

VALIDATION
${report.validationSummary}

LESSONS LEARNED
${report.lessonsLearned?.map((l, i) => `${i + 1}. ${l}`).join("\n") || "None"}

ACTION ITEMS
${report.actionItems?.map(a => `[ ] ${a}`).join("\n") || "None"}
    `.trim();

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `postmortem-${new Date().toISOString().split("T")[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-white dark:bg-slate-900 border border-cyber-border-light dark:border-cyber-border-dark p-6 md:p-8 text-left text-slate-800 dark:text-slate-100 max-w-4xl mx-auto shadow-sm select-text relative">
      {/* Title */}
      <div className="flex flex-col md:flex-row items-center justify-between border-b-2 border-cyber-border-light dark:border-cyber-border-dark pb-6 mb-6 font-mono">
        <div className="text-center md:text-left">
          <h2 className="text-xl md:text-2xl font-bold uppercase tracking-wider text-slate-800 dark:text-slate-100">
            INCIDENT POST-MORTEM REPORT
          </h2>
          <span className="text-[10px] text-slate-400 dark:text-slate-500 uppercase mt-1 block tracking-widest">
            AUTO-GENERATED BY INCIDENT-AGENT // DECOMPOSITION STAGE 9
          </span>
        </div>
        
        <button
          onClick={handleDownload}
          className="mt-4 md:mt-0 flex items-center justify-center gap-2 px-4 py-2 border border-cyber-primary/50 hover:bg-cyber-primary/10 text-cyber-primary font-bold text-xs uppercase tracking-wider transition-all"
        >
          <Download size={14} />
          Export Report
        </button>
      </div>

      <div className="space-y-8 font-sans">
        {/* Executive Summary */}
        <section className="space-y-2.5">
          <h3 className="text-xs font-mono font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400 flex items-center">
            <FileText size={14} className="mr-2 text-cyber-primary" />
            Executive Summary
          </h3>
          <p className="text-xs md:text-sm text-slate-700 dark:text-slate-300 leading-relaxed font-sans">
            {report?.executiveSummary || "Pending executive summary generation..."}
          </p>
        </section>

        {/* Impact */}
        <section className="space-y-2.5">
          <h3 className="text-xs font-mono font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400 flex items-center">
            <Calendar size={14} className="mr-2 text-cyber-accent" />
            Impact Assessment
          </h3>
          <p className="text-xs md:text-sm text-slate-700 dark:text-slate-300 leading-relaxed">
            {report?.impactAssessment || "Pending impact assessment..."}
          </p>
        </section>

        {/* Root Cause Summary */}
        <section className="space-y-2.5 border-l-2 border-red-500/30 pl-4">
          <h3 className="text-xs font-mono font-bold uppercase tracking-widest text-red-500 dark:text-red-400">
            Root Cause Diagnostics
          </h3>
          <p className="text-xs md:text-sm text-slate-700 dark:text-slate-300 leading-relaxed">
            {report?.rootCauseSummary || "Pending root cause summary..."}
          </p>
        </section>

        {/* Timeline */}
        {report?.incidentTimeline && report.incidentTimeline.length > 0 && (
          <section className="space-y-3 font-mono">
            <h3 className="text-xs font-mono font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400 flex items-center">
              Incident Response Timeline
            </h3>
            <ul className="space-y-2 text-xs border border-cyber-border-light dark:border-cyber-border-dark p-4 bg-slate-50 dark:bg-slate-900/30 divide-y divide-cyber-border-light dark:divide-cyber-border-dark">
              {report.incidentTimeline.map((item, idx) => (
                <li key={idx} className="py-2.5 first:pt-0 last:pb-0 text-slate-600 dark:text-slate-400 leading-relaxed">
                  {item}
                </li>
              ))}
            </ul>
          </section>
        )}

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pt-4 border-t border-cyber-border-light dark:border-cyber-border-dark">
          {/* Remediation Summary */}
          <section className="space-y-2.5">
            <h3 className="text-xs font-mono font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400">
              Mitigation Actions Taken
            </h3>
            <p className="text-xs text-slate-700 dark:text-slate-300 leading-relaxed font-sans">
              {report?.remediationSummary || "Pending remediation summary..."}
            </p>
          </section>

          {/* Validation Summary */}
          <section className="space-y-2.5">
            <h3 className="text-xs font-mono font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400 flex items-center">
              <Shield size={14} className="mr-2 text-emerald-500" />
              Safety & Compliance Audit
            </h3>
            <p className="text-xs text-slate-700 dark:text-slate-300 leading-relaxed font-sans">
              {report?.validationSummary || "Pending validation summary..."}
            </p>
          </section>
        </div>

        {/* Lessons Learned */}
        {report?.lessonsLearned && report.lessonsLearned.length > 0 && (
          <section className="space-y-3 pt-4 border-t border-cyber-border-light dark:border-cyber-border-dark">
            <h3 className="text-xs font-mono font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400">
              Lessons Learned
            </h3>
            <ul className="space-y-2 font-sans text-xs text-slate-600 dark:text-slate-400">
              {report.lessonsLearned.map((lesson, idx) => (
                <li key={idx} className="bg-slate-50 dark:bg-slate-900/30 border border-cyber-border-light dark:border-cyber-border-dark px-3 py-2 leading-relaxed">
                  <span className="font-mono text-cyber-primary font-bold mr-2">{idx + 1}.</span>
                  <span>{lesson}</span>
                </li>
              ))}
            </ul>
          </section>
        )}

        {/* Action items */}
        {report?.actionItems && report.actionItems.length > 0 && (
          <section className="space-y-3 pt-4 border-t border-cyber-border-light dark:border-cyber-border-dark">
            <h3 className="text-xs font-mono font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400 flex items-center">
              <CheckSquare size={14} className="mr-2 text-cyber-primary" />
              Recurrence Prevention Action Items
            </h3>
            <ul className="space-y-2 font-mono text-xs">
              {report.actionItems.map((item, idx) => (
                <li key={idx} className="flex items-start space-x-2 text-slate-700 dark:text-slate-300">
                  <span className="text-cyber-primary font-bold">{`[ ]`}</span>
                  <span className="font-sans text-xs leading-relaxed">{item}</span>
                </li>
              ))}
            </ul>
          </section>
        )}
      </div>
    </div>
  );
};
export default PostMortemViewer;
