/**
 * src/constants/pipeline.constants.ts
 *
 * PURPOSE:
 *   Exports canonical names for every pipeline stage and step status value
 *   in the incident response workflow. Prevents magic strings in pipeline.ts,
 *   workflow definitions, and API response mapping.
 *
 *   Without this file, strings like "RUNNING", "DONE", "FAILED" appear as
 *   inline literals in pipeline.ts and IncidentContext.ts. Renaming a stage
 *   requires tracking down every occurrence across the codebase.
 *
 * WHERE IT WILL BE USED:
 *   • src/core/pipeline.ts           — step status string values ("RUNNING" etc.)
 *   • src/models/IncidentContext.ts  — PipelineStepStatus type values
 *   • src/mastra/workflows/          — step name references
 *   • src/api/controllers/           — pipeline status in HTTP responses
 *   • tests/                         — asserting step names and statuses
 *
 * HOW TO VERIFY:
 *   import { PipelineStepStatus, PipelineStageNames } from '../constants/pipeline.constants.ts';
 *   console.assert(PipelineStepStatus.RUNNING === 'RUNNING');
 *   console.assert(PipelineStageNames.CREATED === 'CREATED');
 *   npm run typecheck  →  zero errors
 *
 * DEPENDENCY RULE:
 *   This file MUST NOT import from any other src/ module.
 *   It contains only literal constant values.
 */

// ─────────────────────────────────────────────────────────────────────────────
// § 1. Pipeline Step Status Values
//
//   The execution status of a single IIncidentContextStep as it runs.
//   These values match the PipelineStepStatus union type in IncidentContext.ts.
//   pipeline.ts uses these constants when updating step records.
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Execution status values for a single pipeline step.
 *
 * PENDING  — Step is queued but has not started executing.
 * RUNNING  — Step is currently executing (in-flight async call).
 * DONE     — Step completed successfully.
 * FAILED   — Step encountered an error; see the associated AppError.
 */
export const PipelineStepStatus = {
  PENDING: "PENDING",
  RUNNING: "RUNNING",
  DONE: "DONE",
  FAILED: "FAILED",
} as const;

/** Union type of all valid pipeline step statuses. */
export type PipelineStepStatusValue =
  (typeof PipelineStepStatus)[keyof typeof PipelineStepStatus];

// ─────────────────────────────────────────────────────────────────────────────
// § 2. Pipeline Stage Names
//
//   Each stage represents a logical checkpoint in the incident response
//   pipeline. The names are used as IWorkflowStep.name values — they appear
//   in StepResult records, OpenTelemetry span names, and log output.
//
//   ORDER matters: the stages are listed in their natural execution sequence.
//   Use PIPELINE_STAGE_ORDER (§ 3) when you need the ordered sequence.
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Canonical stage names for the incident response pipeline.
 *
 * CREATED           — Incident context has been initialised from an anomaly signal.
 * PARSED            — Raw log batch has been received and validated.
 * NORMALIZED        — Log entries have been normalised into NormalisedLogEntry[].
 * ANALYZED          — Anomaly detection analysis has completed.
 * MEMORY_RETRIEVED  — Similar past incidents retrieved from Qdrant vector store.
 * ROOT_CAUSE_READY  — LLM root cause analysis has completed successfully.
 * REMEDIATION_READY — Remediation actions have been generated by the LLM.
 * VALIDATED         — Enkrypt AI guardrails validation has completed.
 * REPORT_GENERATED  — Post-mortem report draft has been generated.
 * STORED            — Incident context has been stored in Qdrant for future retrieval.
 */
export const PipelineStageNames = {
  CREATED: "CREATED",
  PARSED: "PARSED",
  NORMALIZED: "NORMALIZED",
  ANALYZED: "ANALYZED",
  MEMORY_RETRIEVED: "MEMORY_RETRIEVED",
  ROOT_CAUSE_READY: "ROOT_CAUSE_READY",
  REMEDIATION_READY: "REMEDIATION_READY",
  VALIDATED: "VALIDATED",
  REPORT_GENERATED: "REPORT_GENERATED",
  STORED: "STORED",
} as const;

/** Union type of all valid pipeline stage names. */
export type PipelineStageName =
  (typeof PipelineStageNames)[keyof typeof PipelineStageNames];

// ─────────────────────────────────────────────────────────────────────────────
// § 3. Ordered Stage Sequence
//
//   The canonical execution order of all pipeline stages.
//   Use this array when building the IncidentContextPipeline step list or
//   when rendering a progress timeline in the UI.
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Ordered array of pipeline stage names, from first to last.
 * The index position of a stage name reflects its position in the pipeline.
 */
export const PIPELINE_STAGE_ORDER: ReadonlyArray<PipelineStageName> = [
  PipelineStageNames.CREATED,
  PipelineStageNames.PARSED,
  PipelineStageNames.NORMALIZED,
  PipelineStageNames.ANALYZED,
  PipelineStageNames.MEMORY_RETRIEVED,
  PipelineStageNames.ROOT_CAUSE_READY,
  PipelineStageNames.REMEDIATION_READY,
  PipelineStageNames.VALIDATED,
  PipelineStageNames.REPORT_GENERATED,
  PipelineStageNames.STORED,
] as const;

/**
 * Total number of stages in the pipeline.
 * Used for progress percentage calculations in the API and UI.
 */
export const TOTAL_PIPELINE_STAGES = PIPELINE_STAGE_ORDER.length;

// ─────────────────────────────────────────────────────────────────────────────
// § 4. Workflow Names
//
//   Canonical identifiers for each named workflow in the system.
//   These match the WorkflowName union in contracts/workflow.contract.ts.
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Named workflow identifiers.
 * Used as the workflowName argument in Pipeline and IncidentContextPipeline
 * constructors, and as keys in the WorkflowRegistry.
 */
export const WorkflowNames = {
  INCIDENT_RESPONSE: "incident-response",
  POST_MORTEM_GENERATION: "post-mortem-generation",
  REMEDIATION_VALIDATION: "remediation-validation",
} as const;

/** Union type of all registered workflow names. */
export type WorkflowNameValue =
  (typeof WorkflowNames)[keyof typeof WorkflowNames];

// ─────────────────────────────────────────────────────────────────────────────
// § 5. Pipeline Timing Constants
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Default timeout for the entire incident response pipeline run in milliseconds.
 * 5 minutes — generous enough for LLM calls, strict enough to prevent hangs.
 */
export const DEFAULT_PIPELINE_TIMEOUT_MS = 300_000 as const; // 5 minutes

/**
 * Default maximum retry count for transient step failures.
 * 0 means steps do not retry by default — opt-in per step.
 */
export const DEFAULT_MAX_RETRIES = 0 as const;

/**
 * Base delay (ms) between retries when using exponential backoff.
 * Formula: BASE_RETRY_DELAY_MS * 2^retryCount
 */
export const BASE_RETRY_DELAY_MS = 1000 as const;
